from flask import Flask, render_template, request
from waitress import serve
import imageMaker.pil_autowrap as pilwrap
import logging
from decouple import config
import psycopg
import os

DATABASE_URL = config('DATABASE_URL')
INSTA_USER = config('INSTA_USER')
INSTA_PWD = config('INSTA_PWD')

logger = logging.getLogger('waitress')
logger.setLevel(logging.DEBUG)
app = Flask(__name__)

conn = psycopg.connect(DATABASE_URL)
with conn.cursor() as cur:
    cur.execute("""
        CREATE TABLE IF NOT EXISTS Posts (
            PostID INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0) PRIMARY KEY, 
            message STRING NOT NULL, 
            name STRING NOT NULL,
            reply_to INT REFERENCES Posts(PostID) ON DELETE SET NULL
        );
    """)
    conn.commit()

@app.route('/', methods=["GET"])
def main():
    return render_template("index.html")

@app.route('/', methods=["POST"])
def post():
    content = request.get_json(silent=True)
    
    if("message" not in content or content["message"] == ""):
        return {"ret": False, "error":"nomsg"}
    
    if("name" not in content or content["name"] == ""):
        name = "Anon"
    else:
        name = content["name"]
        
    #add to DB
    try:
        with conn.cursor() as cur:
            cur.execute(f"INSERT INTO Posts (message, name, reply_to) VALUES ('{content['message']}', '{name}', NULL) RETURNING PostID;")
            res = cur.fetchall()
            conn.commit()
            post_num=res[0][0]
    except:
        return {"ret": False, "error":"dbwrite"}
    
    
    #Make the image
    post_str=f"post#{post_num:05d}"
    try:
        pilwrap.make_text_image(content["message"], name, post_str, (100,100,0,255), post_str)
    except:
        return {"ret": False, "error":"makeimage"}
    
    #post the image
    
    
    #delete the img from temp
    os.remove(f"./temp/{post_str}.png")
    
    return {"ret": True}

if __name__ == "__main__":
    #serve(app, host='0.0.0.0', port=80, threads=8)
    app.run(host='0.0.0.0', port=80)