import psycopg2
from decouple import config

DATABASE_URL = config('DATABASE_URL')

#add to db
conn = psycopg2.connect(DATABASE_URL)

with conn.cursor() as cur:
    #cur.execute("DROP TABLE Posts;")
    cur.execute("""
        CREATE TABLE IF NOT EXISTS Posts (
            PostID INT GENERATED BY DEFAULT AS IDENTITY (INCREMENT 1 MINVALUE 0 START 0) PRIMARY KEY, 
            message STRING NOT NULL, 
            name STRING NOT NULL,
            reply_to INT REFERENCES Posts(PostID) ON DELETE SET NULL
        );
        """)
    cur.execute("""
        
        INSERT INTO Posts (message, name, reply_to) VALUES ( 'Heloo sadasd ', 'sadads', NULL );
                
                """)
    cur.execute("""
        
        SELECT * FROM Posts;
                
                """)
    res = cur.fetchall()
    conn.commit()
    print(res)
